In [ ]:
1+1

2

In [ ]:
print("Notebook Working")

Notebook Working

In [3]:
from statsmodels.regression.rolling import RollingOLS
import pandas_datareader.data as web
import matplotlib.pyplot as plt
import statsmodels.api as sm
import pandas as pd
import numpy as np
import datetime as dt
import yfinance as yf
import pandas_ta
import warnings
warnings.filterwarnings('ignore')

In [4]:
import sys
print(sys.version)

3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

In [5]:
import pandas_ta as ta

print("Installed:", ta.version)

Installed: 0.4.24

In [6]:
import pandas as pd
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
html = response.text

sp500 = pd.read_html(StringIO(html))[0]

In [7]:
sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [8]:
print("Hello")

Hello

In [9]:
sp500['Symbol'] = sp500['Symbol'].str.replace('.','-')

In [10]:
symbols_list = sp500['Symbol'].unique().tolist()

symbols_list=symbols_list[:5]

end_date = pd.Timestamp.today() - pd.Timedelta(days=1)

# '2023-09-27' ko string se datetime me convert karo

start_date = end_date - pd.DateOffset(years=8)

In [17]:
# # Taaki model ke paas kaafi historical data ho indicators banane ke liye:
# failed = []

# for symbol in symbols_list:
#     try:
#         df = yf.download(
#             symbol,
#             start=start_date,
#             end=end_date,
#             auto_adjust=True,
#             threads=False
#         )

#         if df.empty:
#             failed.append(symbol)

#     except:
#         failed.append(symbol)

# print("Failed:", failed)
data = yf.download(
    symbols_list,
    start=start_date,
    end=end_date,
    auto_adjust=True,
    threads=False
)

[**********************80%*************          ]  4 of 5 completed$MMM: possibly delisted; no price data found  (1d 2018-06-18 21:42:16.748033 -> 2026-06-18 21:42:16.748033)
[*********************100%***********************]  5 of 5 completed

1 Failed download:
['MMM']: possibly delisted; no price data found  (1d 2018-06-18 21:42:16.748033 -> 2026-06-18 21:42:16.748033)

In [18]:
data['SMA_20'] = data['Close'].rolling(20).mean()

ValueError: Cannot set a DataFrame with multiple columns to the single column SMA_20

In [13]:
df.stack()

Price                   Close        High         Low        Open    Volume
Date       Ticker
2018-06-19 ACN     145.172729  145.199397  143.385966  144.114889   2574400
2018-06-20 ACN     143.803802  145.226098  143.706019  144.897195   2026800
2018-06-21 ACN     142.256973  143.945953  141.901403  143.448149   2034200
2018-06-22 ACN     141.901443  142.674817  140.843603  142.674817   3623900
2018-06-25 ACN     138.816788  140.505767  138.096749  140.443549   3134500
...                       ...         ...         ...         ...       ...
2026-06-12 ACN     170.279999  171.770004  164.649994  168.440002   4040100
2026-06-15 ACN     165.360001  172.589996  165.050003  167.600006   6026500
2026-06-16 ACN     165.520004  169.789993  165.029999  165.630005   4422600
2026-06-17 ACN     156.009995  166.869995  155.910004  164.899994   7563200
2026-06-18 ACN     127.980003  134.699997  125.599998  126.500000  41701500

[2011 rows x 5 columns]

In [15]:
df.index.names= ['date','ticker']

ValueError: Length of new names must be 1, got 2

In [ ]:
df.columns