In [9]:
import pandas as pd
import numpy as np
import yfinance as yf

In [10]:
# python list are little bit slower
price = [100,200,300,400,500]
mprice= []
for i in price:
    mprice.append(i+10)
print(mprice)

[110, 210, 310, 410, 510]

In [3]:
# python list are little bit slower 
# now perform the same operation on large data set'
# benifit of vectorized operations
    # - can even smooth run on none values
price = [100,200,300,np.nan, 400,500]
npprice = np.array(price)
npprice + 10

array([110., 210., 310.,  nan, 410., 510.])

In [ ]:
# .str accessor missing values ko handle kar leta hai.
ticker = ['APPL','MSFT','META',None,'HPCL']
ser = pd.Series(ticker)

# string operation on Series and on Pandas

#string accessor
ser.str.lower()

0    appl
1    msft
2    meta
3     NaN
4    hpcl
dtype: str

In [7]:
ser.dtype

In [16]:
df = pd.read_csv("../data/raw/constituents-financials.csv")
df

,Symbol,Name,Sector,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings
0,MMM,3M Company,Industrials,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...
1,AOS,A.O. Smith Corp,Industrials,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...
2,ABT,Abbott Laboratories,Health Care,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...
3,ABBV,AbbVie Inc.,Health Care,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...
4,ACN,Accenture plc,Information Technology,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,Xylem Inc.,Industrials,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,http://www.sec.gov/cgi-bin/browse-edgar?action...
501,YUM,Yum! Brands Inc,Consumer Discretionary,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,http://www.sec.gov/cgi-bin/browse-edgar?action...
502,ZBH,Zimmer Biomet Holdings,Health Care,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,http://www.sec.gov/cgi-bin/browse-edgar?action...
503,ZION,Zions Bancorp,Financials,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,http://www.sec.gov/cgi-bin/browse-edgar?action...
504,ZTS,Zoetis,Health Care,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,http://www.sec.gov/cgi-bin/browse-edgar?action...

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Symbol          505 non-null    str
 1   Name            505 non-null    str
 2   Sector          505 non-null    str
 3   Price           505 non-null    float64
 4   Price/Earnings  503 non-null    float64
 5   Dividend Yield  505 non-null    float64
 6   Earnings/Share  505 non-null    float64
 7   52 Week Low     505 non-null    float64
 8   52 Week High    505 non-null    float64
 9   Market Cap      505 non-null    int64
 10  EBITDA          505 non-null    float64
 11  Price/Sales     505 non-null    float64
 12  Price/Book      497 non-null    float64
 13  SEC Filings     505 non-null    str
dtypes: float64(9), int64(1), str(4)
memory usage: 55.4 KB

In [26]:
dfs= df[['Symbol','Name','Sector','SEC Filings']]

In [38]:
# str accessor works on Series not on DataFrame
dfs['Name'].str.lower()
dfs['Name'].str.upper()
dfs['Name'].str.capitalize()
dfs['Name'].str.len()

dfs[dfs['Name'].str.len() > 22]

# it will remove the leading and trailing spaces
dfs['Name'].str.strip()
dfs['Name'].str.split()
dfs[dfs['Name'].str.split().str.len() > 4]

,Symbol,Name,Sector,SEC Filings
15,APD,Air Products & Chemicals Inc,Materials,http://www.sec.gov/cgi-bin/browse-edgar?action...
19,ARE,Alexandria Real Estate Equities Inc,Real Estate,http://www.sec.gov/cgi-bin/browse-edgar?action...
37,AWK,American Water Works Company Inc,Utilities,http://www.sec.gov/cgi-bin/browse-edgar?action...
56,AJG,Arthur J. Gallagher & Co.,Financials,http://www.sec.gov/cgi-bin/browse-edgar?action...
64,BHGE,"Baker Hughes, a GE Company",Energy,http://www.sec.gov/cgi-bin/browse-edgar?action...
202,FBHS,Fortune Brands Home & Security,Industrials,http://www.sec.gov/cgi-bin/browse-edgar?action...
258,JBHT,J. B. Hunt Transport Services,Industrials,http://www.sec.gov/cgi-bin/browse-edgar?action...
277,LH,Laboratory Corp. of America Holding,Health Care,http://www.sec.gov/cgi-bin/browse-edgar?action...
436,BK,The Bank of New York Mellon Corp.,Financials,http://www.sec.gov/cgi-bin/browse-edgar?action...
452,FOXA,Twenty-First Century Fox Class A,Consumer Discretionary,http://www.sec.gov/cgi-bin/browse-edgar?action...
453,FOX,Twenty-First Century Fox Class B,Consumer Discretionary,http://www.sec.gov/cgi-bin/browse-edgar?action...
457,ULTA,Ulta Salon Cosmetics & Fragrance Inc,Consumer Discretionary,http://www.sec.gov/cgi-bin/browse-edgar?action...

In [39]:
# replace
dfs['Name'].str.replace(' ','-')

0                  3M-Company
1             A.O.-Smith-Corp
2         Abbott-Laboratories
3                 AbbVie-Inc.
4               Accenture-plc
                ...
500                Xylem-Inc.
501           Yum!-Brands-Inc
502    Zimmer-Biomet-Holdings
503             Zions-Bancorp
504                    Zoetis
Name: Name, Length: 505, dtype: str

In [45]:
#startswith
dfs[dfs['Name'].str.startswith('A')]
dfs[dfs['Name'].str.endswith('p')]

dfs[(dfs['Name'].str.startswith('A')) & (df['Name'].str.endswith('A'))]

dfs[dfs['Name'].str.isdigit()]
dfs[dfs['Name'].str.isalpha()]

,Symbol,Name,Sector,SEC Filings
22,ALLE,Allegion,Industrials,http://www.sec.gov/cgi-bin/browse-edgar?action...
45,ANDV,Andeavor,Energy,http://www.sec.gov/cgi-bin/browse-edgar?action...
46,ANSS,ANSYS,Information Technology,http://www.sec.gov/cgi-bin/browse-edgar?action...
73,BLK,BlackRock,Financials,http://www.sec.gov/cgi-bin/browse-edgar?action...
76,BWA,BorgWarner,Consumer Discretionary,http://www.sec.gov/cgi-bin/browse-edgar?action...
81,AVGO,Broadcom,Information Technology,http://www.sec.gov/cgi-bin/browse-edgar?action...
100,CERN,Cerner,Health Care,http://www.sec.gov/cgi-bin/browse-edgar?action...
126,COP,ConocoPhillips,Energy,http://www.sec.gov/cgi-bin/browse-edgar?action...
154,DWDP,DowDuPont,Materials,http://www.sec.gov/cgi-bin/browse-edgar?action...
174,EQIX,Equinix,Real Estate,http://www.sec.gov/cgi-bin/browse-edgar?action...
232,HOLX,Hologic,Health Care,http://www.sec.gov/cgi-bin/browse-edgar?action...
245,INCY,Incyte,Health Care,http://www.sec.gov/cgi-bin/browse-edgar?action...
267,KEY,KeyCorp,Financials,http://www.sec.gov/cgi-bin/browse-edgar?action...
288,LYB,LyondellBasell,Materials,http://www.sec.gov/cgi-bin/browse-edgar?action...
290,MAC,Macerich,Real Estate,http://www.sec.gov/cgi-bin/browse-edgar?action...
324,NAVI,Navient,Financials,http://www.sec.gov/cgi-bin/browse-edgar?action...
325,NTAP,NetApp,Information Technology,http://www.sec.gov/cgi-bin/browse-edgar?action...
334,NKE,Nike,Consumer Discretionary,http://www.sec.gov/cgi-bin/browse-edgar?action...
337,JWN,Nordstrom,Consumer Discretionary,http://www.sec.gov/cgi-bin/browse-edgar?action...
348,OKE,ONEOK,Energy,http://www.sec.gov/cgi-bin/browse-edgar?action...
355,PYPL,PayPal,Information Technology,http://www.sec.gov/cgi-bin/browse-edgar?action...
359,PKI,PerkinElmer,Health Care,http://www.sec.gov/cgi-bin/browse-edgar?action...
360,PRGO,Perrigo,Health Care,http://www.sec.gov/cgi-bin/browse-edgar?action...
376,PLD,Prologis,Real Estate,http://www.sec.gov/cgi-bin/browse-edgar?action...
382,QRVO,Qorvo,Information Technology,http://www.sec.gov/cgi-bin/browse-edgar?action...
392,REGN,Regeneron,Health Care,http://www.sec.gov/cgi-bin/browse-edgar?action...
395,RMD,ResMed,Health Care,http://www.sec.gov/cgi-bin/browse-edgar?action...
433,FTI,TechnipFMC,Energy,http://www.sec.gov/cgi-bin/browse-edgar?action...
451,TRIP,TripAdvisor,Consumer Discretionary,http://www.sec.gov/cgi-bin/browse-edgar?action...
504,ZTS,Zoetis,Health Care,http://www.sec.gov/cgi-bin/browse-edgar?action...

In [50]:
# applying regex
dfs[dfs['Name'].str.contains('John')]
dfs[dfs['Name'].str.contains('john',case=False)]

,Symbol,Name,Sector,SEC Filings
261,JNJ,Johnson & Johnson,Health Care,http://www.sec.gov/cgi-bin/browse-edgar?action...
262,JCI,Johnson Controls International,Industrials,http://www.sec.gov/cgi-bin/browse-edgar?action...

In [62]:
# access the last name
dfs['Name'].str.split().str[-1]
dfs['Last_Name'] = dfs['Name'].str.split().str[-1]

In [64]:
dfs['Last_Name']

0           Company
1              Corp
2      Laboratories
3              Inc.
4               plc
           ...
500            Inc.
501             Inc
502        Holdings
503         Bancorp
504          Zoetis
Name: Last_Name, Length: 505, dtype: object

In [ ]:
dfs[(dfs['Last_Name'].str.startswith('C')) & (dfs['Last_Name'].str.endswith('y'))]

,Symbol,Name,Sector,SEC Filings,Last Name
0,MMM,3M Company,Industrials,http://www.sec.gov/cgi-bin/browse-edgar?action...,Company
64,BHGE,"Baker Hughes, a GE Company",Energy,http://www.sec.gov/cgi-bin/browse-edgar?action...,Company
75,BA,Boeing Company,Industrials,http://www.sec.gov/cgi-bin/browse-edgar?action...,Company
168,EMR,Emerson Electric Company,Industrials,http://www.sec.gov/cgi-bin/browse-edgar?action...,Company
314,TAP,Molson Coors Brewing Company,Consumer Staples,http://www.sec.gov/cgi-bin/browse-edgar?action...,Company
437,CLX,The Clorox Company,Consumer Staples,http://www.sec.gov/cgi-bin/browse-edgar?action...,Company
439,HSY,The Hershey Company,Consumer Staples,http://www.sec.gov/cgi-bin/browse-edgar?action...,Company
440,MOS,The Mosaic Company,Materials,http://www.sec.gov/cgi-bin/browse-edgar?action...,Company
442,DIS,The Walt Disney Company,Consumer Discretionary,http://www.sec.gov/cgi-bin/browse-edgar?action...,Company
449,TSCO,Tractor Supply Company,Consumer Discretionary,http://www.sec.gov/cgi-bin/browse-edgar?action...,Company
489,WRK,WestRock Company,Materials,http://www.sec.gov/cgi-bin/browse-edgar?action...,Company

In [61]:
# find last name starting with vowel
df[df['Last Name'].str.contains('^[aeiou]')]

KeyError: 'Last Name'