In [1]:
import pandas as pd
import numpy as np

In [ ]:
# # Number of rows
# num_rows = 1000000

# # Create sample data with 1,000,000 rows
# data = {
#     'Timestamp': pd.date_range(start='2022-01-01', periods=num_rows, freq='S'),
#     'Ticker': (['AAPL', 'GOOGL', 'MSFT', 'BTC', 'ETH', 'XRP'] * ((num_rows // 6) + 1))[:num_rows],
#     'Price': ([150, 2500, 300, 155, 2550, 310] * ((num_rows // 6) + 1))[:num_rows],
#     'Volume': ([100, 200, 150, 110, 210, 160] * ((num_rows // 6) + 1))[:num_rows],
#     'Buy/Sell': (['Buy', 'Sell', 'Buy', 'Sell', 'Buy', 'Sell'] * ((num_rows // 6) + 1))[:num_rows],
#     'Trader_ID': (['T1', 'T2', 'T3', 'T4', 'T5', 'T6'] * ((num_rows // 6) + 1))[:num_rows],
#     'Exchange': (['NYSE', 'NASDAQ', 'NYSE', 'Binance', 'Bybit', 'Coinbase'] * ((num_rows // 6) + 1))[:num_rows]
# }

# # Convert the dictionary into a DataFrame

In [2]:
exchange_df = pd.read_csv("../data/raw/Exchange_Trade_Data.csv")
exchange_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  200000 non-null  int64
 1   Timestamp   200000 non-null  object
 2   Ticker      200000 non-null  object
 3   Price       200000 non-null  int64
 4   Volume      200000 non-null  int64
 5   Buy/Sell    200000 non-null  object
 6   Trader_ID   200000 non-null  object
 7   Exchange    200000 non-null  object
dtypes: int64(3), object(5)
memory usage: 12.2+ MB

In [3]:
exchange_df.head()

,Unnamed: 0,Timestamp,Ticker,Price,Volume,Buy/Sell,Trader_ID,Exchange
0,0,2022-01-01 00:00:00,AAPL,150,100,Buy,T1,NYSE
1,1,2022-01-01 00:00:01,GOOGL,2500,200,Sell,T2,NASDAQ
2,2,2022-01-01 00:00:02,MSFT,300,150,Buy,T3,NYSE
3,3,2022-01-01 00:00:03,BTC,155,110,Sell,T4,Binance
4,4,2022-01-01 00:00:04,ETH,2550,210,Buy,T5,Bybit

In [4]:
exchange_df.shape

(200000, 8)

In [5]:
exchange_df.sample(30)

,Unnamed: 0,Timestamp,Ticker,Price,Volume,Buy/Sell,Trader_ID,Exchange
120872,120872,2022-01-02 09:34:32,MSFT,300,150,Buy,T3,NYSE
147336,147336,2022-01-02 16:55:36,AAPL,150,100,Buy,T1,NYSE
106935,106935,2022-01-02 05:42:15,BTC,155,110,Sell,T4,Binance
40295,40295,2022-01-01 11:11:35,XRP,310,160,Sell,T6,Coinbase
5924,5924,2022-01-01 01:38:44,MSFT,300,150,Buy,T3,NYSE
122824,122824,2022-01-02 10:07:04,ETH,2550,210,Buy,T5,Bybit
187260,187260,2022-01-03 04:01:00,AAPL,150,100,Buy,T1,NYSE
116136,116136,2022-01-02 08:15:36,AAPL,150,100,Buy,T1,NYSE
183014,183014,2022-01-03 02:50:14,MSFT,300,150,Buy,T3,NYSE
67750,67750,2022-01-01 18:49:10,ETH,2550,210,Buy,T5,Bybit
95550,95550,2022-01-02 02:32:30,AAPL,150,100,Buy,T1,NYSE
56457,56457,2022-01-01 15:40:57,BTC,155,110,Sell,T4,Binance
79909,79909,2022-01-01 22:11:49,GOOGL,2500,200,Sell,T2,NASDAQ
49716,49716,2022-01-01 13:48:36,AAPL,150,100,Buy,T1,NYSE
3801,3801,2022-01-01 01:03:21,BTC,155,110,Sell,T4,Binance
176366,176366,2022-01-03 00:59:26,MSFT,300,150,Buy,T3,NYSE
120074,120074,2022-01-02 09:21:14,MSFT,300,150,Buy,T3,NYSE
74432,74432,2022-01-01 20:40:32,MSFT,300,150,Buy,T3,NYSE
34965,34965,2022-01-01 09:42:45,BTC,155,110,Sell,T4,Binance
20460,20460,2022-01-01 05:41:00,AAPL,150,100,Buy,T1,NYSE
71940,71940,2022-01-01 19:59:00,AAPL,150,100,Buy,T1,NYSE
170159,170159,2022-01-02 23:15:59,XRP,310,160,Sell,T6,Coinbase
107691,107691,2022-01-02 05:54:51,BTC,155,110,Sell,T4,Binance
85248,85248,2022-01-01 23:40:48,AAPL,150,100,Buy,T1,NYSE
141041,141041,2022-01-02 15:10:41,XRP,310,160,Sell,T6,Coinbase
106027,106027,2022-01-02 05:27:07,GOOGL,2500,200,Sell,T2,NASDAQ
195260,195260,2022-01-03 06:14:20,MSFT,300,150,Buy,T3,NYSE
118773,118773,2022-01-02 08:59:33,BTC,155,110,Sell,T4,Binance
188504,188504,2022-01-03 04:21:44,MSFT,300,150,Buy,T3,NYSE
169120,169120,2022-01-02 22:58:40,ETH,2550,210,Buy,T5,Bybit

In [7]:
# not good way
# exchange_df.groupby('Ticker').sum()

#good way
exchange_df.groupby('Ticker')['Volume'].sum()

Ticker
AAPL     3333400
BTC      3666630
ETH      6999930
GOOGL    6666800
MSFT     4999950
XRP      5333280
Name: Volume, dtype: int64