In [1]:
print("Hello")
import pandas as pd
import numpy as np

df = pd.DataFrame({"A":[1,2,3]})
df

Hello

   A
0  1
1  2
2  3

In [ ]:
df

In [2]:
print("hello")

import pandas as pd
df = pd.DataFrame({"A":[1,2,3]})

df

hello

   A
0  1
1  2
2  3